# Generated by Django 5.2.5 on 2025-12-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=10)),
                ("phone_no", models.CharField(max_length=10)),
                ("salary", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
