# Generated by Django 5.2.5 on 2026-01-01 05:18

import expense.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Travel", "Travel"),
                    ("Rent", "Rent"),
                    ("Entertainment", "Entertainment"),
                    ("Others", "Others"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(validators=[expense.models.no_future_date]),
        ),
        migrations.AlterField(
            model_name="expense",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
