# Generated by Django 5.2.5 on 2026-01-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_expense_description_alter_expense_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("UPI", "UPI"), ("Card", "Card")],
                default="Cash",
                max_length=10,
            ),
        ),
    ]
