# Generated by Django 5.2.5 on 2026-01-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0004_expense_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="description",
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Transport", "Transport"),
                    ("Bills", "Bills"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Card", "Card"), ("UPI", "UPI")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
