# Generated by Django 5.2.5 on 2026-01-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0005_remove_expense_description_alter_expense_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
