# Generated by Django 5.2.5 on 2026-01-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0006_expense_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="receipt",
        ),
    ]
