# Generated by Django 5.2.5 on 2025-12-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="phone_no",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
